# Generated by Django 3.2 on 2022-11-07 15:28

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_detail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=100, scale=1, size=[720, 660], upload_to='products/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_for_cart',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=100, scale=1, size=[300, 300], upload_to='products/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_presmall',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=100, scale=1, size=[150, 140], upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_big',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=100, scale=1, size=[564, 520], upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_middle',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=100, scale=1, size=[212, 200], upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_small',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=100, scale=1, size=[75, 75], upload_to='products/'),
        ),
    ]
